# Fixtures file hold the dependencies for spec helper

fixtures:
  forge_modules:
    php:
      repo: "puppet/php"
      ref: "4.0.0"     
    redis:
      repo: "thomasvandoren/redis"
      ref: "0.10.0"
    mysql:
      repo: "puppetlabs/mysql"
      ref: "3.9.0"
    apache:
      repo: "puppetlabs/apache"
      ref: "1.10.0"  
    git:
      repo: "puppetlabs/git"
      ref: "0.5.0" 
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "1.4.0" 
    supervisord:
      repo: "ajcrowe/supervisord"
      ref: "0.6.1"
    # Automatic Dependencies
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.13.1" 
    concat:
      repo: "puppetlabs/concat"
      ref: "2.2.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "2.3.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "1.6.0"
    wget:
      repo: "maestrodev/wget"
      ref: "1.7.3"
    gcc:
      repo: "puppetlabs/gcc"
      ref: "0.3.0"
#    staging:
#      repo: "puppetlabs/staging"
#      ref: "2.0.1"
  symlinks:
    cachet: "#{source_dir}"